version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  keydb:
    image: eqalpha/keydb
    container_name: keydb
    volumes:
      - ./data/keydb:/data
    ports:
      - 6379:6379
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: always

  nats-streaming:
    image: nats-streaming
    command: "--config /config/nats.conf"
    volumes:
      - ./nats.conf:/config/nats.conf
      - ./data/nats:/data
    ports:
      - "8222:8222"
      - "4222:4222"
    restart: always

networks:
  default:
    name: hospitium-network
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
